<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="niryo_ned2_dual_arm">
    <!-- This file combines two Ned2 robots facing each other with overlapping workspace -->
    <!-- Each robot has a gripper and camera attached -->
    <!-- Robot 1 (ned1) positioned on the left, facing right -->
    <!-- Robot 2 (ned2) positioned on the right, facing left -->
    <!-- Separation 0.6m between base links -->

    <!-- Import single robot URDF (we'll instantiate it twice with different parameters) -->
    <xacro:include filename="$(find niryo_ned_description)/urdf/ned2/niryo_ned2_param.urdf.xacro"/>
    
    <!-- Include gripper XACRO -->
    <xacro:include filename="$(find niryo_ned_description)/urdf/tools/niryo_gripper1.urdf.xacro"/>

    <!-- Camera Properties -->
    <xacro:property name="cameraWidth" value="0.01"/>
    <xacro:property name="cameraHeight" value="0.037"/>
    <xacro:property name="cameraMass" value="0.05"/>

    <!-- Define a macro for a single Ned2 robot instance -->
    <xacro:macro name="ned2_robot" params="prefix base_x base_y base_z base_yaw">
        <!-- Base -->
        <link name="${prefix}base_link">
            <inertial>
                <origin xyz="-0.008924 0.0001357 0.052392" rpy="0 0 0"/>
                <mass value="0.71142"/>
                <inertia ixx="0.0017" ixy="0.0" ixz="0.0" iyy="0.0017" iyz="0.0" izz="0.0032"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/base_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="-${PI/2} 0 0"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/base_link.stl"/>
                </geometry>
            </collision>
        </link>

        <link name="${prefix}led_ring_link">
        </link>

        <!-- Shoulder -->
        <link name="${prefix}shoulder_link">
            <inertial>
                <origin xyz="-0.031951 0.0080419 0.030675" rpy="0 0 0"/>
                <mass value="0.35056"/>
                <inertia ixx="0.00023875" ixy="2.3853E-08" ixz="2.0596E-06" iyy="0.00032638" iyz="-8.9319E-07"
                         izz="0.00030089"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/shoulder_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/shoulder_link.stl"/>
                </geometry>
            </collision>
        </link>

        <!-- Arm -->
        <link name="${prefix}arm_link">
            <inertial>
                <origin xyz="-0.00096976 0.086432 0.0038832" rpy="0 ${PI} 0"/>
                <mass value="1.0838"/>
                <inertia ixx="0.008194" ixy="0.00015602" ixz="-3.434E-06" iyy="0.0011945" iyz="-0.00031298" izz="0.007915"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI} 0"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/arm_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI} 0"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/arm_link.stl"/>
                </geometry>
            </collision>
        </link>

        <!-- Elbow -->
        <link name="${prefix}elbow_link">
            <inertial>
                <origin xyz="-0.019703 0.037336 -1.7431E-09" rpy="0 ${PI} 0"/>
                <mass value="0.22126"/>
                <inertia ixx="0.00011754" ixy="-1.2314E-05" ixz="-6.2064E-11" iyy="0.00020851" iyz="9.2393E-11"
                         izz="0.00022753"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 ${PI} ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/elbow_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 ${PI} ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/elbow_link.stl"/>
                </geometry>
            </collision>
        </link>

        <!-- Forearm -->
        <link name="${prefix}forearm_link">
            <inertial>
                <origin xyz="-0.0049532 7.8351E-06 0.08106" rpy="0 0 0"/>
                <mass value="0.35686"/>
                <inertia ixx="0.0013664" ixy="-9.6367E-08" ixz="0.00013594" iyy="0.0014781" iyz="-1.4596E-07"
                         izz="0.00023715"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/forearm_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/forearm_link.stl"/>
                </geometry>
            </collision>
        </link>

        <!-- Wrist -->
        <link name="${prefix}wrist_link">
            <inertial>
                <origin xyz="-0.019666 0.037312 0.0" rpy="0 0 0"/>
                <mass value="0.22126"/>
                <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/wrist_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/wrist_link.stl"/>
                </geometry>
            </collision>
        </link>

        <!-- Hand -->
        <link name="${prefix}hand_link">
            <inertial>
                <origin xyz="0 0 0.009" rpy="0 0 0"/>
                <mass value="0.0070027"/>
                <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/collada/hand_link.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 ${-PI/2}"/>
                <geometry>
                    <mesh filename="package://niryo_ned_description/meshes/ned2/stl/hand_link.stl"/>
                </geometry>
            </collision>
        </link>

        <!-- Tool Link -->
        <link name="${prefix}tool_link">
        </link>

        <!-- Camera Link -->
        <link name="${prefix}camera_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${cameraWidth} ${cameraHeight} ${cameraHeight}"/>
                </geometry>
                <material name="Grey">
                    <color rgba="0.7 0.7 0.7 1.0"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <box size="${cameraWidth} ${cameraHeight} ${cameraHeight}"/>
                </geometry>
            </collision>
        </link>

        <!-- Joints -->

        <!-- Base to world -->
        <joint name="${prefix}joint_world" type="fixed">
            <parent link="world"/>
            <child link="${prefix}base_link"/>
            <origin xyz="${base_x} ${base_y} ${base_z}" rpy="0 0 ${base_yaw}"/>
        </joint>

        <!-- Base to shoulder (joint 1) -->
        <joint name="${prefix}joint_1" type="revolute">
            <origin xyz="0 0 0.1013" rpy="0 0 0"/>
            <parent link="${prefix}base_link"/>
            <child link="${prefix}shoulder_link"/>
            <axis xyz="0 0 1"/>
            <limit effort="10.0" velocity="10.0" lower="${(limit_low_shoulder_rotation + safety_pos_margin) * deg_to_rad}"
                   upper="${(limit_up_shoulder_rotation - safety_pos_margin) * deg_to_rad}"/>
        </joint>

        <!-- Shoulder to arm (joint 2) -->
        <joint name="${prefix}joint_2" type="revolute">
            <origin xyz="0 0 0.065" rpy="${PI/2} 0 0"/>
            <parent link="${prefix}shoulder_link"/>
            <child link="${prefix}arm_link"/>
            <axis xyz="0 0 1"/>
            <limit effort="10.0" velocity="8.0" lower="${(limit_low_arm_rotation + safety_pos_margin) * deg_to_rad}"
                   upper="${(limit_up_arm_rotation - safety_pos_margin) * deg_to_rad}"/>
        </joint>

        <!-- Arm to elbow (joint 3) -->
        <joint name="${prefix}joint_3" type="revolute">
            <origin xyz="0.012 0.221 0" rpy="0 0 ${PI/2}"/>
            <parent link="${prefix}arm_link"/>
            <child link="${prefix}elbow_link"/>
            <axis xyz="0 0 1"/>
            <limit effort="7.0" velocity="8.0" lower="${(limit_low_elbow_rotation + safety_pos_margin) * deg_to_rad}"
                   upper="${(limit_up_elbow_rotation - safety_pos_margin) * deg_to_rad}"/>
        </joint>

        <!-- Elbow to forearm (joint 4) -->
        <joint name="${prefix}joint_4" type="revolute">
            <origin xyz="0.0325 -0.065 0" rpy="${PI/2} 0 0"/>
            <parent link="${prefix}elbow_link"/>
            <child link="${prefix}forearm_link"/>
            <axis xyz="0 0 1"/>
            <limit effort="7.0" velocity="2.0" lower="${(limit_low_forearm_rotation + safety_pos_margin) * deg_to_rad}"
                   upper="${(limit_up_forearm_rotation - safety_pos_margin) * deg_to_rad}"/>
        </joint>

        <!-- Forearm to wrist (joint 5) -->
        <joint name="${prefix}joint_5" type="revolute">
            <origin xyz="0 0 0.17" rpy="${-PI/2} 0 0"/>
            <parent link="${prefix}forearm_link"/>
            <child link="${prefix}wrist_link"/>
            <axis xyz="0 0 1"/>
            <limit effort="6.0" velocity="2.0" lower="${(limit_low_wrist_rotation + safety_pos_margin) * deg_to_rad}"
                   upper="${(limit_up_wrist_rotation - safety_pos_margin) * deg_to_rad}"/>
        </joint>

        <!-- Wrist to hand (joint 6) -->
        <joint name="${prefix}joint_6" type="revolute">
            <origin xyz="0.00925 -0.0197 0" rpy="${PI/2} 0 0"/>
            <parent link="${prefix}wrist_link"/>
            <child link="${prefix}hand_link"/>
            <axis xyz="0 0 1"/>
            <limit effort="5.0" velocity="2.0" lower="${(limit_low_hand_rotation + safety_pos_margin) * deg_to_rad}"
                   upper="${(limit_up_hand_rotation - safety_pos_margin) * deg_to_rad}"/>
        </joint>

        <!-- Hand to tool -->
        <joint name="${prefix}hand_tool_joint" type="fixed">
            <parent link="${prefix}hand_link"/>
            <child link="${prefix}tool_link"/>
            <origin xyz="0 0 ${distance_hand_tool}" rpy="${PI} -${PI/2} 0"/>
        </joint>

        <!-- LED ring -->
        <joint name="${prefix}joint_led_ring" type="fixed">
            <parent link="world"/>
            <child link="${prefix}led_ring_link"/>
            <origin xyz="${base_x} ${base_y} ${base_z + 0.0923}" rpy="0 0 ${base_yaw}"/>
        </joint>

        <!-- Joint from tool_link to base_gripper -->
        <joint name="${prefix}joint_to_gripper" type="fixed">
            <parent link="${prefix}tool_link"/>
            <child link="${prefix}base_gripper_1"/>
            <origin xyz="-0.007 0 0.003" rpy="${-PI/2} ${PI/2} 0"/>
        </joint>

        <!-- Gripper instance -->
        <xacro:gripper_1 prefix="${prefix}"/>

        <!-- Wrist to camera -->
        <joint name="${prefix}camera_joint" type="fixed">
            <axis xyz="0 0 1"/>
            <origin xyz="${cameraHeight/2 + 0.02} 0 0" rpy="0 0 ${-PI/2+deg_to_rad*10}"/>
            <parent link="${prefix}wrist_link"/>
            <child link="${prefix}camera_link"/>
        </joint>

    </xacro:macro>

    <!-- World link -->
    <link name="world"/>

    <!-- Instantiate Robot 1 (ned1) Left robot, facing right (yaw = 0) -->
    <!-- Positioned at x = -0.40 (half of 0.8m separation) -->
    <xacro:ned2_robot prefix="ned1_" base_x="-0.40" base_y="0" base_z="0" base_yaw="0"/>

    <!-- Instantiate Robot 2 (ned2) Right robot, facing left (yaw = PI) -->
    <!-- Positioned at x = +0.40 (half of 0.8m  separation) -->
    <xacro:ned2_robot prefix="ned2_" base_x="0.40" base_y="0" base_z="0" base_yaw="${PI}"/>

</robot>
